ALTER TABLE email_monitors
ADD COLUMN IF NOT EXISTS last_email_uid TEXT,
ADD COLUMN IF NOT EXISTS last_email_date TIMESTAMP,
ADD COLUMN IF NOT EXISTS last_email_subject TEXT,
ADD COLUMN IF NOT EXISTS last_email_from TEXT;

ALTER TABLE email_check_logs
ADD COLUMN IF NOT EXISTS emails_skipped_seen INTEGER DEFAULT 0 NOT NULL,
ADD COLUMN IF NOT EXISTS emails_deleted INTEGER DEFAULT 0 NOT NULL,
ADD COLUMN IF NOT EXISTS emails_errored INTEGER DEFAULT 0 NOT NULL,
ADD COLUMN IF NOT EXISTS last_email_uid TEXT,
ADD COLUMN IF NOT EXISTS last_email_date TIMESTAMP,
ADD COLUMN IF NOT EXISTS last_email_subject TEXT,
ADD COLUMN IF NOT EXISTS last_email_from TEXT;
